default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: voice_development

test:
  <<: *default
  database: voice_test

production:
  <<: *default
  database: voice_production
